# Generated by Django 4.2.4 on 2023-09-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='notification_time',
            field=models.CharField(default='19 hours ago', max_length=200),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='notification_message',
            field=models.CharField(default='Dear Sir, Your wire transfer request has been approved. Your account has been debited by $1,010.00 on 29/08/2023 08:25', max_length=200),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='notification_number',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
