# Generated by Django 4.2.4 on 2023-09-04 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0003_deposit_notification_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_loans', models.CharField(default='0', max_length=200, null=True)),
                ('loan_id', models.CharField(default='None', max_length=200)),
                ('next_payment_date', models.CharField(default='None', max_length=200)),
                ('status', models.CharField(default='None', max_length=200)),
                ('amount_to_pay', models.CharField(default='None', max_length=200)),
                ('action', models.CharField(default='None', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
