# Generated by Django 4.2.4 on 2023-09-04 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0004_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='action',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_to_pay',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_payment_date',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.CreateModel(
            name='Transaction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
