# Generated by Django 4.2.4 on 2023-09-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_new_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_payment',
            name='currency',
            field=models.IntegerField(default='-'),
        ),
    ]
