# Generated by Django 4.2.4 on 2023-09-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_new_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_payment',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='new_payment',
            name='currency',
            field=models.CharField(default='USD', max_length=200),
        ),
        migrations.AlterField(
            model_name='new_payment',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='new_payment',
            name='receiver_account',
            field=models.CharField(default='', max_length=200),
        ),
    ]
