# Generated by Django 4.2.4 on 2023-09-05 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0012_alter_new_payment_amount_alter_new_payment_currency_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_payment',
            new_name='Payment',
        ),
    ]
