# Generated by Django 4.2.4 on 2023-09-05 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_rename_new_payment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
