# Generated by Django 4.2.4 on 2023-09-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_deposit_name_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction1',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction2',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
