# Generated by Django 4.2.4 on 2023-09-05 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0018_loan_name_payment_name_transaction_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction1',
            new_name='Transaction1s',
        ),
        migrations.RenameModel(
            old_name='Transaction2',
            new_name='Transaction2s',
        ),
    ]
