# Generated by Django 4.2.4 on 2023-09-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_remove_loan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='active_loans',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
