# Generated by Django 4.2.4 on 2023-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_alter_loan_active_loans_alter_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='action',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_to_pay',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_payment_date',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
    ]
