# Generated by Django 4.2.4 on 2023-09-05 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0025_alter_loan_action_alter_loan_amount_to_pay_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction1',
            new_name='Transactionone',
        ),
        migrations.RenameModel(
            old_name='Transaction2',
            new_name='Transactiontwo',
        ),
    ]
