# Generated by Django 4.2.4 on 2023-09-05 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank', '0027_alter_loan_action_alter_loan_active_loans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactionthree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionfour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactionfive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('currency', models.CharField(default='-', max_length=200)),
                ('amount', models.CharField(default='-', max_length=200)),
                ('charge', models.CharField(default='-', max_length=200)),
                ('grand_total', models.CharField(default='-', max_length=200)),
                ('debit_credit', models.CharField(default='-', max_length=200)),
                ('method', models.CharField(default='-', max_length=200)),
                ('status', models.CharField(default='-', max_length=200)),
                ('details', models.CharField(default='-', max_length=200)),
                ('date_time', models.CharField(default='-', max_length=200)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
