# Generated by Django 4.2.4 on 2023-09-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_alter_report_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcard',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
