# Generated by Django 4.2.4 on 2023-09-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_alter_redeemcard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcard',
            name='name',
            field=models.CharField(default='Amazon Gift Card', max_length=200, null=True),
        ),
    ]
