# Generated by Django 4.2.4 on 2023-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0037_cardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='notification_message',
            field=models.CharField(default='Dear Customer, Your account has succefully been created on 29/08/2023 08:25', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='action',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='active_loans',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_to_pay',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='next_payment_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfive',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionfour',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionone',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactionthree',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='amount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='currency',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='date_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='debit_credit',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='details',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='grand_total',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactiontwo',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
